# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.10.1
_src_path: gh:radio-aktywne/template-meta
accountname: radio-aktywne
description: Liquidsoap app template 🧴
reponame: template-app-liquidsoap
repourl: https://github.com/radio-aktywne/template-app-liquidsoap
templatename: liquidsoap
type: app
